name: Master CI Pipeline

on:
  push:
    branches: [master]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  quality-and-build:
    name: Quality check and build
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.11.0'

      - name: set Yarn version
        run: yarn set version 4.5.1

      - name: install dependencies
        id: install
        run: |
          echo "Installing dependencies..."
          yarn install
          echo "Dependency installation complete!"
        
      - name: test coverage check
        id: test-coverage
        run: yarn test:ci
        env:
          CI: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            ./coverage
            ./reports/junit
          retention-days: 30

      - name: run EsLint
        id: lint
        run: |
          echo "Running ESLint..."
          yarn lint
          echo "ESLint check complete!"

      - name: run TypeScript check
        id: typecheck
        run: |
          echo "Running TypeScript check..."
          yarn type-check
          echo "TypeScript check complete!"

      - name: build project
        id: build
        run: |
          echo "Building project..."
          yarn build
          echo "Build complete!"

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    name: deploy to Github pages
    needs: quality-and-build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: deploy to Github pages
        id: deployment
        uses: actions/deploy-pages@v4